### PR TITLE
regenerate

### PR DESCRIPTION
**Pull request by clason**
Update generated files with current tree-sitter CLI; add generated bindings.

### CODE REVIEW

**Review by caarlos0 — APPROVED** [review]

**Comment by clason** [comment]
Oops, forgot I was using a prerelease ts version. Hang on, I'll fix.

**Comment by clason** [comment]
There you go. You might not want all these bindings, but they are needed for people who want to use your parser in their own standalone project.

**Comment by clason** [comment]
(Note: When regenerating the parser, don't forget to commit the two json in the `/src` directory.)

**Comment by caarlos0** [comment]
thanks @clason 🙏🏻

**Pull request merged**
